### ISSUE TITLE
startup error is reported

### ISSUE THREAD

**Issue by xiaoyan1995** [hayden-fr/ComfyUI-Image-Browsing#1]
The following error occurs at startup:
Traceback (most recent call last):
  File "H:\ai\comfyui\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ai\comfyui\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-image-browsing\__init__.py", line 6, in <module>
    os.symlink("../output", "./web/output")
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '../output' -> './web/output'

Cannot import H:\ai\comfyui\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-image-browsing module for custom nodes: [WinError 3] 系统找不到指定的路径。: '../output' -> './web/output'

**Comment by hayden-cn** [comment]
git pull and try again

**Comment by hayden-cn** [comment]
项目地址已经发生了改变，移除原来的扩展，使用新的地址拉取
```
git clone https://github.com/hayden-fr/ComfyUI-Image-Browsing.git
```
